### ISSUE TITLE
Allow separate logo color for modes currently only supporting ring color

### ISSUE THREAD

**Issue by Lolzen** [KsenijaS/krakenx#22]
An flag to either have a solid color, or none at all on the logo (NZXT text") while maintaining spectrumwave on the ring would be nice.

**Comment by jneumaier** [comment]
Spectrum wave completely ignores all input colors in the protocol as far as I know and tested. See also [PROTOCOL.md](https://github.com/KsenijaS/krakenx/blob/master/PROTOCOL.md). Do you know if this is possible in CAM software?

**Comment by Lolzen** [comment]
It is possiblle on CAM software, hence why i have issued a request for this.

**Comment by jonasmalacofilho** [comment]
@jneumaier logo and ring can be set to different modes.

The third byte specifies which channel to target, sync both, logo only or ring only.

**Comment by jneumaier** [comment]
I will try to fix this soon (hopefully next weekend). If someone starts working on this, please just leave a notice here.

**Comment by jneumaier** [comment]
FYI see "only ring" flag and references in:
https://github.com/jonasmalacofilho/liquidctl/blob/f42213366a3bdca27e4ba66e8b5986f979f1eef3/liquidctl/driver/kraken_two.py#L51-L80

**Comment by jonasmalacofilho** [comment]
We can defer this to #27, as it should come for free with the new driver.

In terms of UI, I think we can infer `logo` vs `ring` vs `sync` from the supplied options (`--text_color` vs `--color<n>`.  But this would depend on #21.

**Comment by jonasmalacofilho** [comment]
Closing as #39 has been merged.
