### ISSUE TITLE
How to reset Fan and Pump Settings?

### ISSUE THREAD

**Issue by varomix** [KsenijaS/krakenx#35]
Hi guys
I set fan and pump speeds using this command

` sudo colctl --fan_speed "(20,30),(30,50),(40,90),(45,100)" --mode spectrumwave --animation_speed 3
`
I would like to reset my settings to defaults?

thank you very much

**Comment by jonasmalacofilho** [comment]
The easiest way would be power down the cooler completely (turn the PSU off or disconnect the USB cable from the motherboard). 

Otherwise, you can simply replicate the defaults.  If I remember them correctly, it should be something like this:

```
sudo colctl --fan_speed "(35,25),(40,35),(45,45),(50,55),(55,75),(60,100)" --pump_speed "(35,60),(40,70),(45,80),(50,90),(55,100),(60,100)" --mode loading --color_count 1 --color0 255,255,255
```

**Comment by varomix** [comment]
Thank you
