### ISSUE TITLE
How to set control modes

### ISSUE THREAD

**Issue by varomix** [KsenijaS/krakenx#36]
Hi
I think my fans are running a bit to hi, I can hear the the fans are a bit loud, maybe is in a Performance mode.
Is there a way to change Control Modes as described in the Website
![image](https://user-images.githubusercontent.com/728059/49479608-db5f7000-f7e0-11e8-8fb4-a612742cfa58.png)

I would love to have it in SIlent mode when I'm just doing basic stuff and Performance only when I need to.

thank you

**Comment by jonasmalacofilho** [comment]
What `fan_speed` and `pump_speed` options have you used?

**Comment by varomix** [comment]
think I'm at defaults cause I turned off everything and disconnected the cooler usbs, as someone said I could reset it.

**Comment by varomix** [comment]
mmmh? I really don't want to get something wrong and kill my cooler
I guess I'll have to install windows and see if that has more control and try to figure it out on linux

thanks

**Comment by jonasmalacofilho** [comment]
You're welcome.

I'll close this issue, but feel free to ask more questions.
