### ISSUE TITLE
No module named "usb" error

### ISSUE THREAD

**Issue by thommstark** [KsenijaS/krakenx#40]
entered 

sudo colctl --mode solid --color0 50,0,90 

and got:

Traceback (most recent call last):
  File "/usr/local/bin/colctl", line 7, in <module>
    import usb.core
ModuleNotFoundError: No module named 'usb'

**Comment by jonasmalacofilho** [comment]
It seems you don't have PyUSB.

What method did you use to install krakenx?

**Comment by thommstark** [comment]
I used

sudo python3 -m pip install krakenx

**Comment by thommstark** [comment]
Just installed pyusb and the command now works. I have a purple light. Thanks!

**Comment by jonasmalacofilho** [comment]
No idea what happened, as pip should have picked it up the first time.

But I'm glad it's working now.
