### ISSUE TITLE
Can't appear to set the text color with marquee mode

### ISSUE THREAD

**Issue by NoakPalander** [KsenijaS/krakenx#44]
If I want to be able to have a white logo paired together with a green circle.
Then the command: sudo colctl --mode marquee --color0 0,255,0 --text_color 255,255,255
Should do the trick, yet the logo is still red (the default color). Even if I enable more than 1 color using the --color_count 2, it won't change it.

**Comment by jneumaier** [comment]
Please have a look at #43 ;-)

I will update the README / project page this weekend.
