### ISSUE TITLE
can it interact with cpu temp?

### ISSUE THREAD

**Issue by mcdull** [KsenijaS/krakenx#45]
Thank you for bringing this to the linux.  I was much much regret that I bought the x73. Huge expensive and do not function well.
In windows cam application, if I started to burn the fpu, the pump and fan would run at full speed.

However, when I use it in linux and started a windows vm for fpu, it will overheat being the liquid temperature going too slow.  Is that a way to also incorporate the cpu temperature, or to deduce the cpu utilization for making the cpu / pump curve?

Thank you.

**Comment by jonasmalacofilho** [comment]
In summary: it's possible, but requires a custom script.

You can find more information about this in [liquidctl#203 (comment)](https://github.com/jonasmalacofilho/liquidctl/issues/203#issuecomment-712573639).
