### ISSUE TITLE
Multiple Kraken Support

### ISSUE THREAD

**Issue by AnthonyRawlinsUoM** [KsenijaS/krakenx#7]
Awesome work. What do I need to do to get this working when I have 2x Kraken X62's in my system?

'lsusb' reports as:
Bus 003 Device 006: ID 1e71:170e NZXT 
Bus 003 Device 008: ID 1e71:170e NZXT 

Nevermind... I found the line.

dev = devices[0]

**Comment by jneumaier** [comment]
Should now be fixed with your (pull request)[https://github.com/KsenijaS/krakenx/pull/8] merged. Please close.
