### ISSUE TITLE
Tai Chi effect

### ISSUE THREAD

**Issue by thevik** [KsenijaS/krakenx#9]
Awesome program! you've saved me the overhead of running a windows VM to control my x62!

Is implementing the Tai Chi effect a possibility? It is the only effect that cam software offers that this program does not. 

Thanks!

**Comment by KsenijaS** [comment]
Hi,

I think I have the newest CAM version and it doesn't include Tai Chi effect. I think I saw it in some previous version. If it comes up in some new version I will implement it.

Thanks

**Comment by jneumaier** [comment]
Implemented in this [pull request](https://github.com/KsenijaS/krakenx/pull/14).

**Comment by jneumaier** [comment]
@thevik You may test the Chaser / Tai Chi effect if you like to. You may also try Windows support without your VM.
